name: Build Android and iOS
on: [push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install node dependencies
        run: yarn install --frozen-lockfile
      - name: Build Android Release
        working-directory: android
        run: ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  build-ios:
    runs-on: macos-latest
    env:
      appName: expoejectioswindows
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install node dependencies
        run: yarn install --frozen-lockfile
      - name: Switch XCode version
        run: sudo xcode-select -s /Applications/Xcode_11.app/Contents/Developer
      - name: Install pod dependencies
        working-directory: ios
        run: pod install
      - name: Build app
        working-directory: ios
        run: |
          xcodebuild -workspace ${{env.appName}}.xcworkspace -scheme ${{env.appName}} archive -archivePath ${{env.appName}}.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./${{env.appName}}.xcarchive -exportPath . -exportOptionsPlist ${{env.appName}}/Info.plist
          mv ${{env.appName}}.ipa ../${{env.appName}}.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.appName}}.ipa
          path: ios/build/
